{
 "title": "FIO - Storage Performance Dashboard",
 "tags": [
  "storage",
  "performance"
 ],
 "time": { "from": "2021-08-30T17:39:00.000Z", "to": "2021-08-30T17:55:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "query": "c7d3fcb2-c025-537a-9496-20250c6e6a27"
   },
   { "name": "data_direction2", "query": "0, 1" },
   {
    "name": "host",
    "query": "{\"find\": \"terms\", \"field\": \"host.keyword\"}"
   },
   {
    "name": "sample",
    "query": "{\"find\": \"terms\", \"field\": \"sample\"}"
   },
   { "name": "Filters" },
   {
    "name": "job_number",
    "query": "{\"find\": \"terms\", \"field\": \"job_number\"}"
   },
   {
    "name": "data_direction",
    "query": "{\"find\": \"terms\", \"field\": \"data_direction.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Test average latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "data_direction: $data_direction AND sample: $sample AND job_number: $job_number",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Bandwidth reported in fio_bw.log",
   "type": "graph",
   "description": "https://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "KBs", "label": "Bandwidth in KiB/sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bandwidth",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "log_name: bw AND job_number: $job_number AND sample: $sample AND data_direction: $data_direction AND host: $host",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "latency reported in fio_lat.log",
   "type": "graph",
   "description": "https://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns", "label": "Latency in ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "latency",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "query": "uuid: $uuid AND job_s $job_sequence  AND server_ip: $server_ip AND data_direction: $data_direction AND log_file: lat AND nodeName: $node_name",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Completion latency reported in fio_clat.log",
   "type": "graph",
   "description": "https://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ns", "label": "completion latency in ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "latency",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null,
        "percents": [ "95" ]
       },
       "type": "percentiles"
      }
     ],
     "query": "uuid: $uuid AND job_sequence: $job_sequence  AND server_ip: $server_ip AND data_direction: $data_direction AND nodeName: $node_name",
     "timeField": "time_ms"
    }
   ]
  },
  {
   "title": "IOPS reported in fio_iops.log",
   "type": "graph",
   "description": "https://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "iops",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "uuid: $uuid AND job_sequence: $job_sequence AND server_ip: $server_ip AND data_direction: $data_direction AND log_file: iop AND nodeName: $node_name",
     "timeField": "time_ms"
    }
   ]
  },
  {
   "title": "Aggregated completion latency across clients.",
   "type": "graph",
   "description": "Calculated through https://github.com/axboe/fio/blob/master/tools/hist/fio-histo-log-pctiles.py ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ns", "label": "Aggregated completion latency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "p95",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "min"
      }
     ],
     "query": "uuid: $uuid AND job_sequence: $job_sequence AND samples: $samples",
     "timeField": "time_ms"
    }
   ]
  }
 ]
}